import { useState, useEffect, useRef } from "react";
import { useParams, Link } from "react-router-dom";
import { Music, ExternalLink, Share2, ArrowLeft, Copy, Check } from "lucide-react";
import { projectId, publicAnonKey } from "@/config/supabase";
import { isFigmaSandbox } from "@/utils/sandbox";

const SERVER = `https://${projectId}.supabase.co/functions/v1/make-server-d124bc75`;

interface Track {
  spotify_track_id: string;
  track_name: string;
  artist: string;
  album?: string;
  album_art: string;
  duration_ms: number;
  duration_formatted?: string;
  reason?: string;
  is_new?: boolean;
  preview_url: string | null;
  spotify_url?: string | null;
}

interface SharedPlaylist {
  id: string;
  title: string;
  description: string;
  mood_tags: string[];
  tracks: Track[];
  prompt?: string;
  created_at: string;
}

function formatDuration(ms: number) {
  const totalSeconds = Math.floor(ms / 1000);
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${minutes}:${seconds.toString().padStart(2, "0")}`;
}

function buildShareText(playlist: SharedPlaylist, shareUrl: string) {
  const topTracks = playlist.tracks
    .slice(0, 3)
    .map((t) => `${t.track_name} - ${t.artist}`)
    .join("\n");
  const remaining = playlist.tracks.length - 3;
  return `🎵 ${playlist.title}\n\n${playlist.description}\n\n${topTracks}\n... and ${remaining} more\n\nListen & save → ${shareUrl}\n\nGenerated by Jams`;
}

export function SharedPlaylistPage() {
  const { id } = useParams<{ id: string }>();
  const [playlist, setPlaylist] = useState<SharedPlaylist | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  const [showShareModal, setShowShareModal] = useState(false);
  const [shareModalVisible, setShareModalVisible] = useState(false);
  const [shareText, setShareText] = useState("I made this playlist for you 🎵");
  const [copyLinkText, setCopyLinkText] = useState("Copy Link");

  const [linkCopiedVisible, setLinkCopiedVisible] = useState(false);
  const linkCopiedTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const shareUrl = `${window.location.origin}/playlist/${id}`;

  useEffect(() => {
    if (!id) return;
    if (isFigmaSandbox()) { setNotFound(true); setLoading(false); return; }
    fetch(`${SERVER}/playlists/${id}`, {
      headers: { Authorization: `Bearer ${publicAnonKey}` },
    })
      .then((res) => {
        if (res.status === 404) { setNotFound(true); setLoading(false); return null; }
        return res.json();
      })
      .then((data) => {
        if (!data) return;
        if (data.error) { setNotFound(true); }
        else {
          setPlaylist(data);
        }
        setLoading(false);
      })
      .catch(() => { setNotFound(true); setLoading(false); });
  }, [id]);

  const openShareModal = () => {
    setShowShareModal(true);
    requestAnimationFrame(() => requestAnimationFrame(() => setShareModalVisible(true)));
  };
  const closeShareModal = () => {
    setShareModalVisible(false);
    setTimeout(() => setShowShareModal(false), 200);
  };

  const showLinkCopiedToast = () => {
    setLinkCopiedVisible(true);
    if (linkCopiedTimer.current) clearTimeout(linkCopiedTimer.current);
    linkCopiedTimer.current = setTimeout(() => setLinkCopiedVisible(false), 2000);
  };

  const handleShareButton = () => {
    if (!playlist) return;
    const isMobile = /iPhone|iPad|Android/i.test(navigator.userAgent) || (navigator.share !== undefined);
    if (isMobile && navigator.share) {
      navigator.share({ title: playlist.title, text: shareText, url: shareUrl }).catch(() => {});
    } else {
      openShareModal();
    }
  };

  const handleCopyLink = async () => {
    try { await navigator.clipboard.writeText(shareUrl); }
    catch { fallbackCopy(shareUrl); }
    setCopyLinkText("✓ Link Copied!");
    showLinkCopiedToast();
    setTimeout(() => setCopyLinkText("Copy Link"), 2000);
  };

  const handleShareAsIs = async () => {
    const full = shareText + "\n" + shareUrl;
    try { await navigator.clipboard.writeText(full); }
    catch { fallbackCopy(full); }
    showLinkCopiedToast();
    closeShareModal();
  };

  const fallbackCopy = (text: string) => {
    const el = document.createElement("textarea");
    el.value = text;
    el.style.cssText = "position:fixed;top:-9999px;left:-9999px;opacity:0;";
    document.body.appendChild(el);
    el.focus(); el.select();
    document.execCommand("copy");
    document.body.removeChild(el);
  };

  const buildFullShareText = () => `${shareText}\n\n${shareUrl}`;

  const getPlatformLinks = () => {
    if (!playlist) return {};
    const fullText = buildFullShareText();
    const encodedText = encodeURIComponent(fullText);
    const encodedUrl = encodeURIComponent(shareUrl);
    return {
      whatsapp: `https://wa.me/?text=${encodedText}`,
      twitter: `https://twitter.com/intent/tweet?text=${encodedText}`,
      telegram: `https://t.me/share/url?url=${encodedUrl}&text=${encodedText}`,
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}`,
      email: `mailto:?subject=${encodeURIComponent(playlist.title)}&body=${encodedText}`,
    };
  };

  const saveToAnyMusicApp = () => {
    if (!playlist) return;
    const trackList = playlist.tracks.map((t) => `${t.track_name} - ${t.artist}`).join("\n");
    try {
      navigator.clipboard.writeText(trackList).catch(() => fallbackCopy(trackList));
    } catch { fallbackCopy(trackList); }
    const encodedTracks = encodeURIComponent(trackList);
    const encodedTitle = encodeURIComponent(playlist.title);
    window.open(`https://www.tunemymusic.com/transfer?source=text&playlistName=${encodedTitle}&songs=${encodedTracks}`, "_blank");
  };

  const totalDuration = playlist?.tracks.reduce((s, t) => s + (t.duration_ms || 0), 0) ?? 0;
  const totalMinutes = Math.floor(totalDuration / 60000);
  const totalHours = Math.floor(totalMinutes / 60);
  const remainingMins = totalMinutes % 60;
  const durationText = totalHours > 0 ? `${totalHours} hr ${remainingMins} min` : `${totalMinutes} min`;

  const renderCover = (size: string) => {
    if (!playlist) return null;
    const artworks = playlist.tracks
      .filter((t) => t.album_art)
      .map((t) => t.album_art)
      .filter((url, i, arr) => arr.indexOf(url) === i)
      .slice(0, 4);
    return (
      <div className={`${size} rounded-2xl overflow-hidden flex-shrink-0 shadow-[0_8px_40px_rgba(0,0,0,0.6)]`}>
        {artworks.length >= 4 ? (
          <div className="w-full h-full grid grid-cols-2 grid-rows-2">
            {artworks.map((url, i) => <img key={i} src={url} alt="" className="w-full h-full object-cover" />)}
          </div>
        ) : artworks.length > 0 ? (
          <img src={artworks[0]} alt="cover" className="w-full h-full object-cover" />
        ) : (
          <div className="w-full h-full bg-white/10 flex items-center justify-center">
            <Music className="w-10 h-10 text-white/20" />
          </div>
        )}
      </div>
    );
  };

  const platforms = getPlatformLinks();

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0a0b0d] px-6 py-12">
        <div className="max-w-3xl mx-auto">
          <div className="h-7 w-24 bg-white/5 rounded-lg animate-pulse mb-10" />
          <div className="flex gap-8 mb-10">
            <div className="w-44 h-44 bg-white/5 rounded-2xl animate-pulse flex-shrink-0" />
            <div className="flex-1 space-y-3 pt-2">
              <div className="h-9 bg-white/5 rounded-lg animate-pulse w-3/4" />
              <div className="h-5 bg-white/5 rounded-lg animate-pulse w-full" />
              <div className="h-5 bg-white/5 rounded-lg animate-pulse w-2/3" />
            </div>
          </div>
          <div className="space-y-3">
            {Array.from({ length: 8 }).map((_, i) => (
              <div key={i} className="h-16 bg-white/5 rounded-xl animate-pulse" />
            ))}
          </div>
        </div>
      </div>
    );
  }

  if (notFound || !playlist) {
    return (
      <div className="min-h-screen bg-[#0a0b0d] flex flex-col items-center justify-center px-6 text-center gap-6">
        <div className="w-16 h-16 rounded-full bg-white/5 flex items-center justify-center mb-2">
          <Music className="w-8 h-8 text-white/20" />
        </div>
        <h1 className="text-white text-2xl font-bold">This playlist doesn't exist or has expired</h1>
        <p className="text-white/40 max-w-sm">The link may be broken or the playlist was removed.</p>
        <Link to="/" className="mt-4 flex items-center gap-2 px-6 py-3 rounded-lg bg-[#4feec5] hover:bg-[#3fd9b5] text-[#0a0b0d] font-bold transition-all">
          <ArrowLeft className="w-4 h-4" /> Go to Jams
        </Link>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0a0b0d]">
      <header className="border-b border-[#2A3432] px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2.5 text-white hover:text-[#4feec5] transition-colors">
            <div className="w-7 h-7 rounded-lg bg-[#4feec5] flex items-center justify-center">
              <Music className="w-4 h-4 text-[#0a0b0d]" />
            </div>
            <span className="font-bold text-lg tracking-tight">Jams</span>
          </Link>
          <Link to="/" className="flex items-center gap-1.5 text-white/40 hover:text-white text-sm transition-colors">
            <ArrowLeft className="w-4 h-4" />
            Back to app
          </Link>
        </div>
      </header>

      <div className="max-w-3xl mx-auto px-6 py-10">
        <div className="bg-white/5 backdrop-blur-xl rounded-3xl p-8 border border-[#2A3432] mb-8">
          <div className="flex flex-col sm:flex-row gap-7 items-start">
            {renderCover("w-40 h-40")}
            <div className="flex-1 min-w-0">
              <h1 className="text-3xl font-bold text-white leading-tight mb-2">{playlist.title}</h1>
              {playlist.description && (
                <p className="text-white/60 leading-relaxed mb-4">{playlist.description}</p>
              )}
              <div className="flex items-center gap-4 text-white/40 text-sm mb-6">
                <span>{playlist.tracks.length} songs</span>
                {totalMinutes > 0 && <><span>•</span><span>{durationText}</span></>}
              </div>
              <div className="flex flex-wrap gap-3">
                <button
                  onClick={saveToAnyMusicApp}
                  className="flex items-center gap-2 px-5 py-2.5 rounded-lg bg-[#4feec5] hover:bg-[#3fd9b5] text-[#0a0b0d] font-bold text-sm transition-all"
                >
                  <Music className="w-4 h-4" />
                  Save This Playlist
                  <ExternalLink className="w-3.5 h-3.5 opacity-60" />
                </button>
                <button
                  onClick={handleShareButton}
                  className="flex items-center gap-2 px-5 py-2.5 rounded-lg bg-white/10 hover:bg-white/20 text-white font-semibold text-sm transition-all border border-[#2A3432]"
                >
                  <Share2 className="w-4 h-4" />
                  Share Playlist
                </button>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white/5 backdrop-blur-xl rounded-2xl border border-[#2A3432] overflow-hidden mb-8">
          <div className="px-6 py-4 border-b border-[#2A3432]">
            <h2 className="text-white font-semibold">Tracks</h2>
          </div>
          <div className="divide-y divide-[#2A3432]">
            {playlist.tracks.map((track, index) => (
              <div key={track.spotify_track_id || index} className="px-6 py-4 flex items-center gap-4 hover:bg-white/5 transition-all">
                <span className="w-6 text-center text-white/30 text-sm flex-shrink-0">{index + 1}</span>
                <div className="w-11 h-11 bg-white/10 rounded-md overflow-hidden flex-shrink-0">
                  {track.album_art ? (
                    <img src={track.album_art} alt={track.album || ""} className="w-full h-full object-cover" />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center">
                      <Music className="w-4 h-4 text-white/20" />
                    </div>
                  )}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-white font-medium text-sm truncate">{track.track_name}</p>
                  <p className="text-white/50 text-xs truncate">{track.artist}</p>
                </div>
                <span className="text-white/30 text-xs flex-shrink-0 tabular-nums">
                  {track.duration_formatted || (track.duration_ms ? formatDuration(track.duration_ms) : "—")}
                </span>
              </div>
            ))}
          </div>
        </div>

        <div className="border-t border-[#2A3432] pt-10 text-center">
          <div className="w-12 h-12 rounded-2xl bg-[#4feec5]/10 flex items-center justify-center mx-auto mb-4">
            <Music className="w-6 h-6 text-[#4feec5]" />
          </div>
          <p className="text-white font-bold text-xl mb-2">🎵 Create your own AI playlist</p>
          <p className="text-white/40 text-sm mb-6">Describe any vibe and Jams builds the perfect playlist for you — instantly.</p>
          <Link
            to="/"
            className="inline-flex items-center gap-2 px-8 py-3.5 rounded-xl bg-[#4feec5] hover:bg-[#3fd9b5] text-[#0a0b0d] font-bold text-sm transition-all shadow-[0_0_30px_rgba(79,238,197,0.25)]"
          >
            Generate My Own →
          </Link>
        </div>
      </div>

      {/* Share Modal */}
      {showShareModal && (
        <div
          className="fixed inset-0 z-[70] flex items-center justify-center p-4"
          style={{ opacity: shareModalVisible ? 1 : 0, transition: "opacity 200ms ease" }}
        >
          <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={closeShareModal} />
          <div
            className="relative w-full max-w-[460px] bg-[#1a1b20] border border-[#2A3432] rounded-2xl shadow-2xl overflow-hidden"
            style={{
              transform: shareModalVisible ? "scale(1) translateY(0)" : "scale(0.96) translateY(12px)",
              transition: "transform 200ms ease",
            }}
          >
            <div className="flex items-center justify-between px-6 pt-6 pb-4 border-b border-[#2A3432]">
              <h2 className="text-white font-bold text-lg">Share this playlist</h2>
              <button onClick={closeShareModal} className="text-white/40 hover:text-white transition-colors">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div className="px-6 py-5 space-y-5">
              <div>
                <label className="block text-white/40 text-xs mb-2">✏️ Your message</label>
                <textarea
                  id="share-message"
                  name="share-message"
                  value={shareText}
                  onChange={(e) => setShareText(e.target.value)}
                  rows={2}
                  className="w-full bg-white/5 border border-[#2A3432] rounded-lg px-4 py-3 text-white/80 text-sm leading-relaxed focus:outline-none focus:border-[#4feec5]/50 transition-all resize-none"
                />
              </div>
              <div>
                <label className="block text-white/40 text-xs mb-2">🔗 Playlist link</label>
                <div className="flex items-center gap-2 px-4 py-3 rounded-lg bg-white/5 border border-[#2A3432]">
                  <span className="flex-1 text-white/40 text-xs truncate select-all">{shareUrl}</span>
                  <button
                    onClick={handleCopyLink}
                    className="flex items-center gap-1.5 flex-shrink-0 text-xs font-medium transition-colors"
                    style={{ color: copyLinkText === "✓ Copied!" ? "#4feec5" : "rgba(255,255,255,0.5)" }}
                  >
                    {copyLinkText === "✓ Copied!" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                    {copyLinkText === "✓ Copied!" ? "Copied!" : "Copy"}
                  </button>
                </div>
              </div>
              <div className="grid grid-cols-3 sm:grid-cols-5 gap-2">
                {[
                  { key: "whatsapp", label: "WhatsApp", icon: <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/></svg> },
                  { key: "twitter", label: "Twitter/X", icon: <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg> },
                  { key: "telegram", label: "Telegram", icon: <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor"><path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.96 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z"/></svg> },
                  { key: "facebook", label: "Facebook", icon: <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg> },
                  { key: "email", label: "Email", icon: <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg> },
                ].map(({ key, label, icon }) => (
                  <a
                    key={key}
                    href={platforms[key as keyof typeof platforms]}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex flex-col items-center gap-1.5 px-2 py-3 rounded-xl bg-white/5 hover:bg-white/10 text-white transition-all border border-[#2A3432] hover:border-[#2A3432]"
                  >
                    {icon}
                    <span className="text-[10px] text-white/50">{label}</span>
                  </a>
                ))}
              </div>
              <button
                onClick={handleCopyLink}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-white/5 hover:bg-white/10 border border-[#2A3432] hover:border-[#2A3432] text-white/80 text-sm font-medium transition-all"
              >
                {copyLinkText === "✓ Link Copied!" ? <Check className="w-4 h-4 text-[#4feec5]" /> : <Copy className="w-4 h-4" />}
                <span className={copyLinkText === "✓ Link Copied!" ? "text-[#4feec5]" : ""}>{copyLinkText}</span>
              </button>
              <p className="text-white/25 text-xs text-center">
                For Instagram: copy the link and paste it into your post or story caption
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Copy confirmation toast */}
      <div
        className="fixed bottom-6 left-1/2 z-[80] pointer-events-none"
        style={{
          transform: `translateX(-50%) translateY(${linkCopiedVisible ? "0" : "20px"})`,
          opacity: linkCopiedVisible ? 1 : 0,
          transition: "all 200ms ease",
        }}
      >
        <div className="flex items-center gap-2 px-4 py-2.5 bg-[#1a1b20] border border-[#2A3432] rounded-xl shadow-xl text-white text-sm font-medium whitespace-nowrap">
          <Check className="w-4 h-4 text-[#4feec5]" />
          ✓ Link copied to clipboard
        </div>
      </div>
    </div>
  );
}
